/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DnaIndexRouteImport } from './routes/dna.index'
import { Route as AnalyzeIndexRouteImport } from './routes/analyze.index'
import { Route as ResearchIdRouteImport } from './routes/research.$id'
import { Route as DnaSymbolRouteImport } from './routes/dna.$symbol'
import { Route as AnalyzeSymbolRouteImport } from './routes/analyze.$symbol'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaIndexRoute = DnaIndexRouteImport.update({
  id: '/dna/',
  path: '/dna/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIndexRoute = AnalyzeIndexRouteImport.update({
  id: '/analyze/',
  path: '/analyze/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResearchRoute,
} as any)
const DnaSymbolRoute = DnaSymbolRouteImport.update({
  id: '/dna/$symbol',
  path: '/dna/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeSymbolRoute = AnalyzeSymbolRouteImport.update({
  id: '/analyze/$symbol',
  path: '/analyze/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ask': typeof AskRoute
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/pulse': typeof PulseRoute
  '/radar': typeof RadarRoute
  '/research': typeof ResearchRouteWithChildren
  '/signup': typeof SignupRoute
  '/analyze/$symbol': typeof AnalyzeSymbolRoute
  '/dna/$symbol': typeof DnaSymbolRoute
  '/research/$id': typeof ResearchIdRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/dna/': typeof DnaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ask': typeof AskRoute
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/pulse': typeof PulseRoute
  '/radar': typeof RadarRoute
  '/research': typeof ResearchRouteWithChildren
  '/signup': typeof SignupRoute
  '/analyze/$symbol': typeof AnalyzeSymbolRoute
  '/dna/$symbol': typeof DnaSymbolRoute
  '/research/$id': typeof ResearchIdRoute
  '/analyze': typeof AnalyzeIndexRoute
  '/dna': typeof DnaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ask': typeof AskRoute
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/pulse': typeof PulseRoute
  '/radar': typeof RadarRoute
  '/research': typeof ResearchRouteWithChildren
  '/signup': typeof SignupRoute
  '/analyze/$symbol': typeof AnalyzeSymbolRoute
  '/dna/$symbol': typeof DnaSymbolRoute
  '/research/$id': typeof ResearchIdRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/dna/': typeof DnaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/ask'
    | '/compare'
    | '/login'
    | '/news'
    | '/pulse'
    | '/radar'
    | '/research'
    | '/signup'
    | '/analyze/$symbol'
    | '/dna/$symbol'
    | '/research/$id'
    | '/analyze/'
    | '/dna/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/ask'
    | '/compare'
    | '/login'
    | '/news'
    | '/pulse'
    | '/radar'
    | '/research'
    | '/signup'
    | '/analyze/$symbol'
    | '/dna/$symbol'
    | '/research/$id'
    | '/analyze'
    | '/dna'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/ask'
    | '/compare'
    | '/login'
    | '/news'
    | '/pulse'
    | '/radar'
    | '/research'
    | '/signup'
    | '/analyze/$symbol'
    | '/dna/$symbol'
    | '/research/$id'
    | '/analyze/'
    | '/dna/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AskRoute: typeof AskRoute
  CompareRoute: typeof CompareRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  PulseRoute: typeof PulseRoute
  RadarRoute: typeof RadarRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SignupRoute: typeof SignupRoute
  AnalyzeSymbolRoute: typeof AnalyzeSymbolRoute
  DnaSymbolRoute: typeof DnaSymbolRoute
  AnalyzeIndexRoute: typeof AnalyzeIndexRoute
  DnaIndexRoute: typeof DnaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna/': {
      id: '/dna/'
      path: '/dna'
      fullPath: '/dna/'
      preLoaderRoute: typeof DnaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/': {
      id: '/analyze/'
      path: '/analyze'
      fullPath: '/analyze/'
      preLoaderRoute: typeof AnalyzeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/dna/$symbol': {
      id: '/dna/$symbol'
      path: '/dna/$symbol'
      fullPath: '/dna/$symbol'
      preLoaderRoute: typeof DnaSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$symbol': {
      id: '/analyze/$symbol'
      path: '/analyze/$symbol'
      fullPath: '/analyze/$symbol'
      preLoaderRoute: typeof AnalyzeSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResearchRouteChildren {
  ResearchIdRoute: typeof ResearchIdRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchIdRoute: ResearchIdRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AskRoute: AskRoute,
  CompareRoute: CompareRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  PulseRoute: PulseRoute,
  RadarRoute: RadarRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SignupRoute: SignupRoute,
  AnalyzeSymbolRoute: AnalyzeSymbolRoute,
  DnaSymbolRoute: DnaSymbolRoute,
  AnalyzeIndexRoute: AnalyzeIndexRoute,
  DnaIndexRoute: DnaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
